server:
  port: 9090

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mrm-system
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Explicitly set the Hibernate dialect for MySQL
        dialect: org.hibernate.dialect.MySQL8Dialect